name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to the latest version

      # Optional: Build step if required (e.g., npm run build)
      # Uncomment if you need to run a build command
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'  # Updated to latest node version

      # - name: Install Dependencies
      #   run: npm install  # Install dependencies if using a package manager like npm or yarn

      # - name: Build Project
      #   run: npm run build  # Run build command if required

      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v4  # Updated to the latest version
        with:
          name: github-pages  # Ensure this name matches the one in the pages job
          path: ./  # Ensure this path points to your deployable files (e.g., ./dist if using a build folder)

  pages:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Updated to the latest version
