name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./ # Adjust the path if necessary

  pages:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
