name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./ # Ensure this path points to deployable files

  pages:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
